"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { GalleryThumbnails, FileText, Mic, Film, Code2, Info } from "lucide-react";
import Image from "next/image";

export default function GalleryPage() {
  // In a real app, this data would come from state management or an API
  const generatedItems = {
    text: [
      { id: "t1", title: "My First Note", content: "This is a sample note generated by the AI...", date: "2023-10-26" },
      { id: "t2", title: "Blog Post Idea", content: "Exploring the future of renewable energy sources...", date: "2023-10-25" },
    ],
    audio: [
      { id: "a1", title: "Ambient Soundscape", duration: "0:45", date: "2023-10-24", placeholderUrl: "https://placehold.co/300x200.png", dataAiHint: "sound wave" },
      { id: "a2", title: "Lo-fi Beat", duration: "2:15", date: "2023-10-23", placeholderUrl: "https://placehold.co/300x200.png", dataAiHint: "music notes" },
    ],
    video: [
      { id: "v1", title: "City Timelapse", duration: "0:30", date: "2023-10-22", placeholderUrl: "https://placehold.co/300x200.png", dataAiHint: "cityscape video" },
    ],
    software: [
       { id: "s1", name: "Interactive Quiz App", description: "A small quiz application built with JavaScript.", date: "2023-10-21", placeholderUrl: "https://placehold.co/300x200.png", dataAiHint: "code editor" },
    ],
  };

  const renderEmptyState = (itemType: string) => (
    <div className="text-center py-12">
      <Info className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
      <h3 className="text-xl font-semibold text-foreground mb-2">No {itemType} Generated Yet</h3>
      <p className="text-muted-foreground">
        Start creating {itemType.toLowerCase()} using our AI tools, and they will appear here.
      </p>
    </div>
  );

  return (
    <div className="container mx-auto py-8">
      <Card className="w-full shadow-crimson border-border">
        <CardHeader>
           <div className="flex items-center gap-2 mb-2">
            <GalleryThumbnails className="h-8 w-8 text-primary" />
            <CardTitle className="text-3xl font-bold text-primary">Unified Multimedia Gallery</CardTitle>
          </div>
          <CardDescription>
            Access and manage all your AI-generated text, audio, video, and software projects.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="text" className="w-full">
            <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 mb-6">
              <TabsTrigger value="text" className="py-2 text-base"><FileText className="mr-2 h-5 w-5" />Text</TabsTrigger>
              <TabsTrigger value="audio" className="py-2 text-base"><Mic className="mr-2 h-5 w-5" />Audio</TabsTrigger>
              <TabsTrigger value="video" className="py-2 text-base"><Film className="mr-2 h-5 w-5" />Video</TabsTrigger>
              <TabsTrigger value="software" className="py-2 text-base"><Code2 className="mr-2 h-5 w-5" />Software</TabsTrigger>
            </TabsList>

            <TabsContent value="text">
              {generatedItems.text.length === 0 ? renderEmptyState("Text Snippets") : (
                <div className="space-y-4">
                  {generatedItems.text.map(item => (
                    <Card key={item.id} className="shadow-sm hover:shadow-crimson transition-shadow duration-200">
                      <CardHeader>
                        <CardTitle className="text-xl">{item.title}</CardTitle>
                        <CardDescription>Generated on: {item.date}</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <p className="text-sm text-muted-foreground line-clamp-3">{item.content}</p>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </TabsContent>

            <TabsContent value="audio">
              {generatedItems.audio.length === 0 ? renderEmptyState("Audio Files") : (
                <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                  {generatedItems.audio.map(item => (
                    <Card key={item.id} className="shadow-sm hover:shadow-crimson transition-shadow duration-200">
                       <Image src={item.placeholderUrl} alt={item.title} width={300} height={200} className="rounded-t-lg w-full object-cover aspect-[3/2]" data-ai-hint={item.dataAiHint} />
                      <CardHeader>
                        <CardTitle className="text-xl">{item.title}</CardTitle>
                        <CardDescription>Duration: {item.duration} | Generated: {item.date}</CardDescription>
                      </CardHeader>
                      <CardContent>
                         {/* Placeholder for audio player */}
                        <div className="h-10 bg-muted rounded-md flex items-center justify-center text-sm text-muted-foreground">Audio Player Placeholder</div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </TabsContent>

            <TabsContent value="video">
               {generatedItems.video.length === 0 ? renderEmptyState("Videos") : (
                <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                  {generatedItems.video.map(item => (
                    <Card key={item.id} className="shadow-sm hover:shadow-crimson transition-shadow duration-200">
                      <Image src={item.placeholderUrl} alt={item.title} width={300} height={200} className="rounded-t-lg w-full object-cover aspect-[3/2]" data-ai-hint={item.dataAiHint} />
                      <CardHeader>
                        <CardTitle className="text-xl">{item.title}</CardTitle>
                        <CardDescription>Duration: {item.duration} | Generated: {item.date}</CardDescription>
                      </CardHeader>
                      <CardContent>
                        {/* Placeholder for video player */}
                        <div className="h-32 bg-muted rounded-md flex items-center justify-center text-sm text-muted-foreground">Video Player Placeholder</div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </TabsContent>

            <TabsContent value="software">
              {generatedItems.software.length === 0 ? renderEmptyState("Software Projects") : (
                 <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                  {generatedItems.software.map(item => (
                    <Card key={item.id} className="shadow-sm hover:shadow-crimson transition-shadow duration-200">
                      <Image src={item.placeholderUrl} alt={item.name} width={300} height={200} className="rounded-t-lg w-full object-cover aspect-[3/2]" data-ai-hint={item.dataAiHint} />
                      <CardHeader>
                        <CardTitle className="text-xl">{item.name}</CardTitle>
                         <CardDescription>Created: {item.date}</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <p className="text-sm text-muted-foreground line-clamp-2">{item.description}</p>
                         {/* Placeholder for link to IDE or project */}
                        <div className="mt-2 text-sm text-accent hover:underline cursor-pointer">Open in IDE (Placeholder)</div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
}
